name: Build and Push Docker Image

on:
  workflow_dispatch:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: commit
      uses: prompt/actions-commit-hash@v3
    - uses: docker/setup-buildx-action@v3
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        export DOCKER_TAG=`date -I`-${{ steps.commit.outputs.short }}
        echo Building docker with tag: ${DOCKER_TAG}
        docker buildx create --name "builder" --use
        docker buildx build \
          --cache-to type=registry,ref=orlevi/rvc:cache \
          --cache-from type=registry,ref=orlevi/rvc:cache \
          -t "orlevi/rvc:${DOCKER_TAG}" \
          --push .
